//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinClean.resources {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WinClean.resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die strings.ArgParse.Error ähnelt.
        /// </summary>
        public static string ArgParse_Error {
            get {
                return ResourceManager.GetString("ArgParse.Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die strings.ArgParse.Help ähnelt.
        /// </summary>
        public static string ArgParse_Help {
            get {
                return ResourceManager.GetString("ArgParse.Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die strings.ArgParse.LocaleNotFound ähnelt.
        /// </summary>
        public static string ArgParse_LocaleNotFound {
            get {
                return ResourceManager.GetString("ArgParse.LocaleNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die strings.ArgParse.PartNotFound ähnelt.
        /// </summary>
        public static string ArgParse_PartNotFound {
            get {
                return ResourceManager.GetString("ArgParse.PartNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die strings.ArgParse.PartNotNumerical ähnelt.
        /// </summary>
        public static string ArgParse_PartNotNumerical {
            get {
                return ResourceManager.GetString("ArgParse.PartNotNumerical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die strings.ArgParse.SkippingLanguageSelection ähnelt.
        /// </summary>
        public static string ArgParse_SkippingLanguageSelection {
            get {
                return ResourceManager.GetString("ArgParse.SkippingLanguageSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die strings.CancelEventMessage ähnelt.
        /// </summary>
        public static string CancelEventMessage {
            get {
                return ResourceManager.GetString("CancelEventMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die strings.EarlyDevelopmentMessage ähnelt.
        /// </summary>
        public static string EarlyDevelopmentMessage {
            get {
                return ResourceManager.GetString("EarlyDevelopmentMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die strings.EnterToContinue ähnelt.
        /// </summary>
        public static string EnterToContinue {
            get {
                return ResourceManager.GetString("EnterToContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die strings.EnterToExit ähnelt.
        /// </summary>
        public static string EnterToExit {
            get {
                return ResourceManager.GetString("EnterToExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die strings.ExitingWithExitCode ähnelt.
        /// </summary>
        public static string ExitingWithExitCode {
            get {
                return ResourceManager.GetString("ExitingWithExitCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die strings.FatalErrorOccured ähnelt.
        /// </summary>
        public static string FatalErrorOccured {
            get {
                return ResourceManager.GetString("FatalErrorOccured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die strings.LanguageSelectionTitle ähnelt.
        /// </summary>
        public static string LanguageSelectionTitle {
            get {
                return ResourceManager.GetString("LanguageSelectionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die strings.NotWindows ähnelt.
        /// </summary>
        public static string NotWindows {
            get {
                return ResourceManager.GetString("NotWindows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die strings.NotWindows10 ähnelt.
        /// </summary>
        public static string NotWindows10 {
            get {
                return ResourceManager.GetString("NotWindows10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die strings.Part1.ActivationCheck.Error ähnelt.
        /// </summary>
        public static string Part1_ActivationCheck_Error {
            get {
                return ResourceManager.GetString("Part1.ActivationCheck.Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die strings.Part1.ActivationKey.Request ähnelt.
        /// </summary>
        public static string Part1_ActivationKey_Request {
            get {
                return ResourceManager.GetString("Part1.ActivationKey.Request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die strings.Part1.ActivationKey.Request.Name ähnelt.
        /// </summary>
        public static string Part1_ActivationKey_Request_Name {
            get {
                return ResourceManager.GetString("Part1.ActivationKey.Request.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die strings.Part1.ActivationKeyInstallation.Error ähnelt.
        /// </summary>
        public static string Part1_ActivationKeyInstallation_Error {
            get {
                return ResourceManager.GetString("Part1.ActivationKeyInstallation.Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die strings.Part1.ActivationKeyInstallation.Installing ähnelt.
        /// </summary>
        public static string Part1_ActivationKeyInstallation_Installing {
            get {
                return ResourceManager.GetString("Part1.ActivationKeyInstallation.Installing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die strings.Part1.ActivationKeyInstalled ähnelt.
        /// </summary>
        public static string Part1_ActivationKeyInstallation_Success {
            get {
                return ResourceManager.GetString("Part1.ActivationKeyInstallation.Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die strings.Part1.AlreadyActivated ähnelt.
        /// </summary>
        public static string Part1_AlreadyActivated {
            get {
                return ResourceManager.GetString("Part1.AlreadyActivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die strings.Part1.HasActivationKey.Selection ähnelt.
        /// </summary>
        public static string Part1_HasActivationKey_Selection {
            get {
                return ResourceManager.GetString("Part1.HasActivationKey.Selection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die strings.Part1.HasActivationKey.Selection.Error ähnelt.
        /// </summary>
        public static string Part1_HasActivationKey_Selection_Error {
            get {
                return ResourceManager.GetString("Part1.HasActivationKey.Selection.Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die strings.Part1.HasActivationKey.Selection.No ähnelt.
        /// </summary>
        public static string Part1_HasActivationKey_Selection_No {
            get {
                return ResourceManager.GetString("Part1.HasActivationKey.Selection.No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die strings.Part1.HasActivationKey.Selection.Skip ähnelt.
        /// </summary>
        public static string Part1_HasActivationKey_Selection_Skip {
            get {
                return ResourceManager.GetString("Part1.HasActivationKey.Selection.Skip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die strings.Part1.HasActivationKey.Selection.Yes ähnelt.
        /// </summary>
        public static string Part1_HasActivationKey_Selection_Yes {
            get {
                return ResourceManager.GetString("Part1.HasActivationKey.Selection.Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die strings.Part1.Intro ähnelt.
        /// </summary>
        public static string Part1_Intro {
            get {
                return ResourceManager.GetString("Part1.Intro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die strings.Part1.KmsServer.Request ähnelt.
        /// </summary>
        public static string Part1_KmsServer_Request {
            get {
                return ResourceManager.GetString("Part1.KmsServer.Request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die strings.Part1.KmsServer.Request.Name ähnelt.
        /// </summary>
        public static string Part1_KmsServer_Request_Name {
            get {
                return ResourceManager.GetString("Part1.KmsServer.Request.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die strings.Part1.KmsServer.Selection ähnelt.
        /// </summary>
        public static string Part1_KmsServer_Selection {
            get {
                return ResourceManager.GetString("Part1.KmsServer.Selection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die strings.Part1.KmsServer.Selection.DontKnow ähnelt.
        /// </summary>
        public static string Part1_KmsServer_Selection_DontKnow {
            get {
                return ResourceManager.GetString("Part1.KmsServer.Selection.DontKnow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die strings.Part1.KmsServer.Selection.Error ähnelt.
        /// </summary>
        public static string Part1_KmsServer_Selection_Error {
            get {
                return ResourceManager.GetString("Part1.KmsServer.Selection.Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die stringsPart1.KmsServer.Selection.No ähnelt.
        /// </summary>
        public static string Part1_KmsServer_Selection_No {
            get {
                return ResourceManager.GetString("Part1.KmsServer.Selection.No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die strings.Part1.KmsServer.Selection.Yes ähnelt.
        /// </summary>
        public static string Part1_KmsServer_Selection_Yes {
            get {
                return ResourceManager.GetString("Part1.KmsServer.Selection.Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die strings.Part1.KmsServer.Setting ähnelt.
        /// </summary>
        public static string Part1_KmsServer_Setting {
            get {
                return ResourceManager.GetString("Part1.KmsServer.Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die strings.Part1.KmsServer.Setting.Error ähnelt.
        /// </summary>
        public static string Part1_KmsServer_Setting_Error {
            get {
                return ResourceManager.GetString("Part1.KmsServer.Setting.Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die strings.Part1.KmsServer.Setting.Success ähnelt.
        /// </summary>
        public static string Part1_KmsServer_Setting_Success {
            get {
                return ResourceManager.GetString("Part1.KmsServer.Setting.Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die strings.Part1.NotUsingKmsServer ähnelt.
        /// </summary>
        public static string Part1_NotUsingKmsServer {
            get {
                return ResourceManager.GetString("Part1.NotUsingKmsServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die strings.Part1.Title ähnelt.
        /// </summary>
        public static string Part1_Title {
            get {
                return ResourceManager.GetString("Part1.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die strings.Part1.TitleWindow ähnelt.
        /// </summary>
        public static string Part1_TitleWindow {
            get {
                return ResourceManager.GetString("Part1.TitleWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die strings.Part1.UserSkippedActivation ähnelt.
        /// </summary>
        public static string Part1_UserSkippedActivation {
            get {
                return ResourceManager.GetString("Part1.UserSkippedActivation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die strings.Part1.WindowsActivating ähnelt.
        /// </summary>
        public static string Part1_WindowsActivating {
            get {
                return ResourceManager.GetString("Part1.WindowsActivating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die strings.Part1.WindowsActivation.Error ähnelt.
        /// </summary>
        public static string Part1_WindowsActivation_Error {
            get {
                return ResourceManager.GetString("Part1.WindowsActivation.Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die strings.Part1.WindowsActivation.Success ähnelt.
        /// </summary>
        public static string Part1_WindowsActivation_Success {
            get {
                return ResourceManager.GetString("Part1.WindowsActivation.Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die strings.Part1.WindowsEditions ähnelt.
        /// </summary>
        public static string Part1_WindowsEditions {
            get {
                return ResourceManager.GetString("Part1.WindowsEditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die strings.Part1.WindowsEditions.BoughtOrSkip ähnelt.
        /// </summary>
        public static string Part1_WindowsEditions_BoughtOrSkip {
            get {
                return ResourceManager.GetString("Part1.WindowsEditions.BoughtOrSkip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die strings.Part1.WindowsEditions.ContinueOrInstructions ähnelt.
        /// </summary>
        public static string Part1_WindowsEditions_ContinueOrInstructions {
            get {
                return ResourceManager.GetString("Part1.WindowsEditions.ContinueOrInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die strings.Part1.WindowsEditions.LearnMore ähnelt.
        /// </summary>
        public static string Part1_WindowsEditions_LearnMore {
            get {
                return ResourceManager.GetString("Part1.WindowsEditions.LearnMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die strings.Part1.WindowsEditions.OpeningInstructions ähnelt.
        /// </summary>
        public static string Part1_WindowsEditions_OpeningInstructions {
            get {
                return ResourceManager.GetString("Part1.WindowsEditions.OpeningInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die strings.Part1.WindowsEditions.OpeningLink ähnelt.
        /// </summary>
        public static string Part1_WindowsEditions_OpeningLink {
            get {
                return ResourceManager.GetString("Part1.WindowsEditions.OpeningLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die strings.Part1.WindowsEditions.OpenMessage ähnelt.
        /// </summary>
        public static string Part1_WindowsEditions_OpenMessage {
            get {
                return ResourceManager.GetString("Part1.WindowsEditions.OpenMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die strings.Part1.WindowsEditions.Overview ähnelt.
        /// </summary>
        public static string Part1_WindowsEditions_Overview {
            get {
                return ResourceManager.GetString("Part1.WindowsEditions.Overview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die strings.Part1.WindowsEditions.Overview.Home ähnelt.
        /// </summary>
        public static string Part1_WindowsEditions_Overview_Home {
            get {
                return ResourceManager.GetString("Part1.WindowsEditions.Overview.Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die strings.Part1.WindowsEditions.Overview.Pro ähnelt.
        /// </summary>
        public static string Part1_WindowsEditions_Overview_Pro {
            get {
                return ResourceManager.GetString("Part1.WindowsEditions.Overview.Pro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die strings.Part1.WindowsEditions.Overview.ProForWorkstations ähnelt.
        /// </summary>
        public static string Part1_WindowsEditions_Overview_ProForWorkstations {
            get {
                return ResourceManager.GetString("Part1.WindowsEditions.Overview.ProForWorkstations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die strings.Part1.WindowsEditions.Selection ähnelt.
        /// </summary>
        public static string Part1_WindowsEditions_Selection {
            get {
                return ResourceManager.GetString("Part1.WindowsEditions.Selection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die strings.Part1.WindowsEditions.Selection.Error ähnelt.
        /// </summary>
        public static string Part1_WindowsEditions_Selection_Error {
            get {
                return ResourceManager.GetString("Part1.WindowsEditions.Selection.Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die strings.Part1.WindowsEditions.Selection.Home ähnelt.
        /// </summary>
        public static string Part1_WindowsEditions_Selection_Home {
            get {
                return ResourceManager.GetString("Part1.WindowsEditions.Selection.Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die strings.Part1.WindowsEditions.Selection.Pro ähnelt.
        /// </summary>
        public static string Part1_WindowsEditions_Selection_Pro {
            get {
                return ResourceManager.GetString("Part1.WindowsEditions.Selection.Pro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die strings.Part1.WindowsEditions.Selection.ProForWorkstations ähnelt.
        /// </summary>
        public static string Part1_WindowsEditions_Selection_ProForWorkstations {
            get {
                return ResourceManager.GetString("Part1.WindowsEditions.Selection.ProForWorkstations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die strings.Part1.WindowsEditions.Selection.Skip ähnelt.
        /// </summary>
        public static string Part1_WindowsEditions_Selection_Skip {
            get {
                return ResourceManager.GetString("Part1.WindowsEditions.Selection.Skip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die strings.Part1.WindowsEditions.SupportNote ähnelt.
        /// </summary>
        public static string Part1_WindowsEditions_SupportNote {
            get {
                return ResourceManager.GetString("Part1.WindowsEditions.SupportNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die strings.Select ähnelt.
        /// </summary>
        public static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die strings.Selection.Language ähnelt.
        /// </summary>
        public static string Selection_Language {
            get {
                return ResourceManager.GetString("Selection.Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die strings.Selection.Language.AnsEnglish ähnelt.
        /// </summary>
        public static string Selection_Language_AnsEnglish {
            get {
                return ResourceManager.GetString("Selection.Language.AnsEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die strings.Selection.Language.AnsGerman ähnelt.
        /// </summary>
        public static string Selection_Language_AnsGerman {
            get {
                return ResourceManager.GetString("Selection.Language.AnsGerman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die strings.Selection.Language.CurrentLanguage ähnelt.
        /// </summary>
        public static string Selection_Language_CurrentLanguage {
            get {
                return ResourceManager.GetString("Selection.Language.CurrentLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die strings.Selection.Language.CurrentLanguage.Correct ähnelt.
        /// </summary>
        public static string Selection_Language_CurrentLanguage_Correct {
            get {
                return ResourceManager.GetString("Selection.Language.CurrentLanguage.Correct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die strings.Selection.Language.CurrentLanguage.Wrong ähnelt.
        /// </summary>
        public static string Selection_Language_CurrentLanguage_Wrong {
            get {
                return ResourceManager.GetString("Selection.Language.CurrentLanguage.Wrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die strings.SelectionEmpty ähnelt.
        /// </summary>
        public static string SelectionEmpty {
            get {
                return ResourceManager.GetString("SelectionEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die strings.SelectionNotInRange ähnelt.
        /// </summary>
        public static string SelectionNotInRange {
            get {
                return ResourceManager.GetString("SelectionNotInRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die strings.SelectionNotNumerical ähnelt.
        /// </summary>
        public static string SelectionNotNumerical {
            get {
                return ResourceManager.GetString("SelectionNotNumerical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die strings.WelcomeMessage ähnelt.
        /// </summary>
        public static string WelcomeMessage {
            get {
                return ResourceManager.GetString("WelcomeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die strings.WelcomeTitle ähnelt.
        /// </summary>
        public static string WelcomeTitle {
            get {
                return ResourceManager.GetString("WelcomeTitle", resourceCulture);
            }
        }
    }
}
